version: '3.7'

services:
  mysql:
    container_name: posterr_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=posterr_docker
    ports:
      - '3306:3306'
    expose:
      - '3306'
